### ISSUE TITLE
[BUG] Library logs `ERRO EOF` when everything works properly 

### ISSUE THREAD

**Issue by michalbakowski-monterail** [becoded/go-harvest#19]
Hi, 

## Description
I use the library to load TimeEntries and Users and it works correctly, but library logs `ERRO EOF` for no particular reason.

## Expected Behavior
Library does not log `ERRO EOF` when there is no error

## Actual Behavior

Just run any `HarvestClient` method. (Go 1.15, macOS). If you need more details or a working example let me know. I think they are not needed.

## Attachments

Probably caused by: https://github.com/becoded/go-harvest/blob/master/harvest/harvest.go#L211

```
defer func() {
		// Drain up to 512 bytes and close the body to let the Transport reuse the connection
		if _, err := io.CopyN(ioutil.Discard, resp.Body, 512); err != nil {
			logrus.Error(err)
		}

		if err := resp.Body.Close(); err != nil {
			logrus.Error(err)
		}
	}()
```

`io.CopyN()` may return `err` set to `EOF`

```
// EOF is the error returned by Read when no more input is available.
// Functions should return EOF only to signal a graceful end of input.
// If the EOF occurs unexpectedly in a structured data stream,
// the appropriate error is either ErrUnexpectedEOF or some other error
// giving more detail.
var EOF = errors.New("EOF")
```

**Comment by becoded** [comment]
Thx for already digging into this.

Fixed it in https://github.com/becoded/go-harvest/pull/20

**Comment by michalbakowski-monterail** [comment]
@becoded Thanks :)
