### ISSUE TITLE
date_test fails if local time is not UTC due to parallel execution

### ISSUE THREAD

**Issue by jozseftiborcz** [becoded/go-harvest#39]
## Description
In my local environment local timezone is CET. But test fixtures use time.UTC, therefore in case of parallel execution the setting of time.Local global value will interfere with date_test.go execution.

## Expected Behavior
Tests should run without error.

## Actual Behavior
1. Set local timezone anything other than UTC.
2. run tests

Tests in date_test.go will fail. Eg. TestDate_UnmarshalJSON/Typical_json

## Solution
Either we can use time.UTC in date_test.go instead of time.Local, or we can delete t.Parallel statements in date_test.go.

**Comment by becoded** [comment]
Resolved in #43
